- name: Setup KDE Plasma desktop
  hosts: localhost
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
    - KDE Plasma/minimal
